apiVersion: v1
kind: ResourceQuota
metadata:
  name: movie-app-quota
spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    persistentvolumeclaims: "2"
    services: "3"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: movie-app-limits
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
