apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx:1.21.6
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: production
        - name: BACKEND_HOST
          value: "backend-service"
        - name: BACKEND_PORT
          value: "3000"
