---
# This YAML configuration sets up a Kubernetes stack for Loki, a log aggregation system.
# It includes the following resources:
#
# 1. Namespace:
#    - Creates a dedicated namespace named "logging" for the Loki application.
#
# 2. ServiceAccount:
#    - Defines a ServiceAccount named "loki" in the "logging" namespace for Loki's deployment.
#
# 3. Service:
#    - Exposes Loki as a NodePort service on port 31000.
#    - Maps port 3100 on the container to port 31000 on the node.
#    - Uses a selector to target pods labeled with "app: loki".
#
# 4. Deployment:
#    - Deploys Loki with a single replica.
#    - Specifies the container image "grafana/loki:2.9.4".
#    - Mounts a ConfigMap volume to provide Loki's configuration file.
#    - Uses the "loki" ServiceAccount for permissions.
#
# 5. ConfigMap:
#    - Provides Loki's configuration file under the name "loki-config".
#    - Configures Loki with settings for server, ingester, schema, storage, limits, chunk store, and table manager.
#    - Enables local storage for logs and sets retention policies.
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: logging
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: logging
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 31000
  selector:
    app: loki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      serviceAccountName: loki
      containers:
      - name: loki
        image: grafana/loki:2.9.4
        ports:
        - containerPort: 3100
        args:
        - -config.file=/etc/loki/local-config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/loki/
      volumes:
      - name: config
        configMap:
          name: loki-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: logging
data:
  local-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 0
    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_location: /tmp/loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /tmp/loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h