name: CI/CD Pipeline

# This GitHub Actions workflow automates the CI/CD process for a Kubernetes application stack.
# 
# Trigger:
# - The workflow is triggered on `push` and `pull_request` events targeting the `main` branch.
# 
# Jobs:
# 1. build-and-push:
#    - Runs on `ubuntu-latest`.
#    - Steps:
#      - Checks out the code from the repository.
#      - Sets up Docker Buildx for multi-platform builds.
#      - Logs in to Docker Hub using credentials stored in GitHub Secrets.
#      - Builds and pushes a Docker image to Docker Hub with the tag `llm-app:latest`.
# 
# 2. deploy:
#    - Depends on the `build-and-push` job.
#    - Runs on `ubuntu-latest`.
#    - Steps:
#      - Checks out the code from the repository.
#      - Sets up `kubectl` for interacting with Kubernetes clusters.
#      - Configures the Kubernetes context using a kubeconfig file stored in GitHub Secrets.
#      - Deploys the application to Kubernetes by applying `Deployment.yaml` and `Service.yaml` manifests.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/llm-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f Deployment.yaml
          kubectl apply -f Service.yaml
