# This GitHub Actions workflow automates the deployment of a Kubernetes application.
# 
# Workflow Name: Kubernetes Deployment
# 
# Trigger:
# - The workflow is triggered on a push event to the `main` branch.
# 
# Jobs:
# - deploy:
#   - Runs on the latest Ubuntu environment (`ubuntu-latest`).
#   - Steps:
#     1. **Checkout code**:
#        - Uses the `actions/checkout@v3` action to clone the repository.
#     2. **Set up kubectl**:
#        - Uses the `azure/setup-kubectl@v3` action to install the latest version of `kubectl`.
#     3. **Set up Kubeconfig**:
#        - Configures the Kubernetes context using the `KUBECONFIG` secret.
#        - Exports the kubeconfig file to the current working directory.
#     4. **Apply Kubernetes manifests**:
#        - Executes `kubectl apply -f .` to apply all Kubernetes manifest files in the repository.
name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f .