# This GitHub Actions workflow is designed to perform a vulnerability scan on a Docker image using Trivy.
# 
# Workflow Name:
#   Trivy Image Scan
#
# Trigger Events:
#   - pull_request: Executes the workflow when a pull request is made to the 'main' branch.
#   - push: Executes the workflow when changes are pushed to the 'main' branch.
#
# Jobs:
#   trivy-scan:
#     - Runs on the latest Ubuntu environment.
#     - Steps:
#       1. Checkout code: Uses the 'actions/checkout' action to fetch the repository code.
#       2. Set up Docker Buildx: Configures Docker Buildx for building multi-platform images.
#       3. Build Docker image: Builds a Docker image tagged as 'movie-app:ci' using the repository's Dockerfile.
#       4. Run Trivy vulnerability scanner: Scans the built Docker image for vulnerabilities using the 'aquasecurity/trivy-action'.
#          - image-ref: Specifies the Docker image to scan ('movie-app:ci').
#          - format: Outputs the scan results in a table format.
#          - exit-code: Sets the exit code to 1 if vulnerabilities are found.
#          - ignore-unfixed: Ignores vulnerabilities that do not have fixes available.
#          - vuln-type: Scans for both OS and library vulnerabilities.
name: Trivy Image Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t movie-app:ci .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.16.2
        with:
          image-ref: movie-app:ci
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
